# 定义数据库信息
SQLALCHEMY_DATABASE_URI = ''
SQLALCHEMY_POOL_RECYCLE = 3600
SQLALCHEMY_POOL_SIZE = 1000
SQLALCHEMY_MAX_OVERFLOW = -1
SQLALCHEMY_POOL_TIMEOUT = 120
SQLALCHEMY_TRACK_MODIFICATIONS = False

# 定义flask信息
SECRET_KEY = ''
WHITELIST_UA = ''
WTF_CSRF_ENABLED = False

# 定义邮件信息
MAIL_SERVER = None
MAIL_PORT = 25
MAIL_USE_SSL = False
MAIL_USERNAME = None
MAIL_PASSWORD = None
MAIL_DEFAULT_SENDER = None

# 定义redis信息
REDIS_URL = ''
